version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db  # volume persistant pour SQLite
    environment:
      - DJANGO_DB_ENGINE=mysql
      - MYSQL_HOST=db_mysql
      - MYSQL_DATABASE=polls_db
      - MYSQL_USER=polls_user
      - MYSQL_PASSWORD=pollspass
    depends_on:
      - db_mysql
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: polls_db
      MYSQL_USER: polls_user
      MYSQL_PASSWORD: pollspass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  sqlite_data:
  mysql_data: